### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ubmarco** [tuxedocomputers/tuxedo-fan-control#1]
When trying to build the package on Arch, I get various errors like:
```
Error /home/marco/tuxedo-fan-control/node_modules/@types/selenium-webdriver/remote.d.ts (139,29): Cannot find name 'Map'.
Error /home/marco/tuxedo-fan-control/output/dist/electronmain.ts (258,31): Property 'find' does not exist on type 'CommandlineOption[]'.
Error: Cannot find global value 'Promise'.
Error /home/marco/tuxedo-fan-control/output/dist/common/daemonworker.ts (2,24): Cannot find module './system'.
```
I attached the full [build.log](https://github.com/tuxedocomputers/tuxedo-fan-control/files/2586996/build.log)

Any hints what I'm doing wrong?

**Comment by tuxedochris** [comment]
Hi Marco,

first, this is not a real error, reather a warning in this case. I know this problem and this stands on my todo list. Currently but i work on the ec communication. After finish the work on the ec communication i would fix this.

Cheers
Chris

**Comment by ubmarco** [comment]
Hello Chris,
thanks for investigating! I don't have the impression these are warnings because the build stops and the log contains a lot of errors. Is there a workaround for me until the problem gets fixed? I also tried to build on an 18.04.1 LTS Ubuntu machine with the same issues. I have NodeJS 10.13 installed.

**Comment by tuxedochris** [comment]
Hi Marco,

what the build stops? As i said, thats are warning messages and the build process should be completed, even with these errors.

Can you try a build with "npm run build" and then start the application with "npm run start"?

Cheers
Chris

**Comment by tuxedochris** [comment]
Hi Marco,

I forgot, you must start the program with sudo privileges
Steps:
1. npm run build
2. sudo su
3. npm run start

Cheers
Chris

**Comment by tuxedochris** [comment]
Hi Marco,

we have fix the issue. Pull the current Master code and build the new version.

Cheers
Chris
